### ISSUE TITLE
Build pipeline

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/edges#13]
It would be good to be able to create builds more easily - at the moment just shell scripts when needed.  Attempts to use require were ultimately unsatisfactory, so should back all of that experimentation out.

It would be nice to be able to:

* Build the entire library into a single file
* Build selected portions of the library into a single file (for focused builds around a specific interface that doesn't use all of edges capabilities)

This obviously relates to dependencies between modules too, which we should sort out.

**Comment by codedfile** [comment]
#14
